# Generated by Django 4.1.3 on 2022-12-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
