# Generated by Django 4.1.3 on 2022-12-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='p_phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='depart_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(),
        ),
    ]
