# Generated by Django 4.1.3 on 2022-12-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_booking_p_phone_alter_booking_depart_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(auto_now=True),
        ),
    ]
