# Generated by Django 4.1.3 on 2022-12-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_booking_booked_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
    ]
