# Generated by Django 4.1.3 on 2022-12-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_remove_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
